### ISSUE TITLE
Add "SankeyColumn" Column to Index table

### ISSUE THREAD

**Issue by kenny5033** [Energy-Visualizer/mexer#91]
Adding a column to the Index table that define where that industry / energy carrier goes in a Sankey diagram.

**Comment by MatthewHeun** [comment]
See the Index tab of the attached file. Will this work?

[SchemaAndFKTables2.xlsx](https://github.com/user-attachments/files/17911611/SchemaAndFKTables2.xlsx)

**Comment by MatthewHeun** [comment]
Closed in favor of #67, which is where we will track testing of the new SankeyColumn column.
