### ISSUE TITLE
Asking for the U_EIOU matrix delivered the U matrix

### ISSUE THREAD

**Issue by MatthewHeun** [Energy-Visualizer/mexer#93]
When I configure Mexer like this:

<img width="736" alt="image" src="https://github.com/user-attachments/assets/d404b575-ff73-463b-b4a3-2f6c8c894a6c">

I get the attached download. 

[eviz_data.csv](https://github.com/user-attachments/files/17894414/eviz_data.csv)

The download includes only the U matrix, not the U_EIOU matrix. The download should include only the U_EIOU matrix.

**Comment by kenny5033** [comment]
Note to self: U_EIOU should be one of the values in the matrix column in the PSUT table, so it *should* be automatically grabbed by our query.

**Comment by kenny5033** [comment]
Note to self:
1. Fix problem with not being able to get IEA data on eviz_kenny
2. SQL is going for matname = 5. Ensure this is correct and make sure table has correct values for matname = 5.

**Comment by kenny5033** [comment]
Note:
Most importantly, I am unable to replicate this issue. I have, though, tried looking everywhere for where this could be going wrong and can find nothing.

**Comment by MatthewHeun** [comment]
Tried it again now. The problem no longer exists.
